---
- name: configure ansible hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: upgrade the apt servers
  apt:
    update_cache: true
    upgrade: full

- name: Copy the modules configs
  copy:
    src: k8s.conf
    dest: /etc/modules-load.d/k8s.conf

- name: Copy sysctl config file
  copy:
    src: k8s-crio.conf
    dest: /etc/sysctl.d/90-k8s-crio.conf

- name: enable cgroup memory on raspberry pi
  block:
    - name: read the content of the cmdline.txt
      shell: cat /boot/firmware/cmdline.txt
      register: cmdline
      when: ansible_architecture == "aarch64"

    - debug: var=cmdline
      when: ansible_architecture == "aarch64"

    - name: write new cmdline
      lineinfile:
        path: /boot/firmware/cmdline.txt
        regex: '^dwc_otg.lpm.*'
        line: '{{ cmdline.stdout }} cgroup_enable=memory cgroup_memory=1'
        state: present
      when: ansible_architecture == "aarch64" and not cmdline.stdout is search("cgroup_enable")

- name: install necesarry packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'nfs-common', 'netfilter-persistent', 'lvm2']
    state: present
    update_cache: yes

- name: create iptables folder
  file:
    path: /etc/iptables
    state: directory

- name: configure firewall
  template:
    src: iptables-rules.j2
    dest: /etc/iptables/iptables.rules

- name: install rules in iptables
  shell: iptables-restore < /etc/iptables/iptables.rules
  notify: netfilter-persistent start


