---
- name: install cri-o runtime
  block:
    - name: add cri-o stable repository key
      ansible.builtin.apt_key:
        url: 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ OS }}/Release.key'
        state: present

    - name: add cri-o version repository key
      ansible.builtin.apt_key:
        url: 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ VERSION }}/{{ OS }}/Release.key'
        state: present


    - name: add cri-o stable repository
      ansible.builtin.apt_repository:
        repo: 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ OS }}/ /'
        filename: 'devel:kubic:libcontainers:stable.list'

    - name: add cri-o version repository
      ansible.builtin.apt_repository:
        repo: 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ VERSION }}/{{ OS }}/ /'
        filename: 'devel:kubic:libcontainers:stable:cri-o:{{ VERSION }}'

    - name: install cri-o runtime
      apt:
        name: ['cri-o', 'cri-o-runc']
        state: present
        update_cache: yes
    
    - name: add cri-o cgroup driver
      copy:
        src: 02-cgroup-manager.conf
        dest: /etc/crio/crio.conf.d/02-cgroup-manager.conf
      notify:
        - daemon-reload
        - start crio 

