---
- name: add docker
  block:
    - name: add docker repo.key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu groovy stable"
        state: present

    - name: install docker packages
      apt: 
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present
        update_cache: true
      notify: 
        - start docker
        - start containerd
