- name: Provision our cluster with metallb
  hosts: master
  tasks:
    - name: transfer the shell script
      copy: src=files/metallb.sh dest=/home/david mode=0777

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: ./metallb.sh 
        owner: david 
        group: david 
        mode: '0777'

    - name: execute metallb script
      command: ./metallb.sh
